services:
    sitemap_bundle.helper.sitemap:
        class: Adamski\Symfony\SitemapBundle\Helper\SitemapHelper
        arguments:
            - '@service_container'
            - '@router'

    sitemap_bundle.controller.sitemap:
        class: Adamski\Symfony\SitemapBundle\Controller\SitemapController
        arguments:
            - '@sitemap_bundle.helper.sitemap'
        tags:
            - { name: controller.service_arguments }
        calls:
            - [ setContainer, [ '@service_container' ] ]
        public: true

    Adamski\Symfony\SitemapBundle\Helper\SitemapHelper:
        alias: sitemap_bundle.helper.sitemap

    Adamski\Symfony\SitemapBundle\Controller\SitemapController:
        alias: sitemap_bundle.controller.sitemap
        public: true
